[package]
name = "skat-game"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.14.1"
tokio = { version = "1.48.0", features = [ "full" ] }
proto = { path = "../proto/" }
postcard = { version = "1.1.3", features = [ "use-std" ] }

[build-dependencies]
slint-build = "1.14.1"
