[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = [ "full" ] }
proto = { path = "../proto/" }
macros = { path = "../macros" }
rand = "0.9.2"
heapless = "0.9.2"
serde_json = "1.0.148"
async-trait = "0.1.89"
