[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = [ "full" ] }
proto = { path = "../proto/" }
rand = "0.9.2"
postcard = { version = "1.1.3", features = [ "use-std" ] }
heapless = "0.9.2"
